spring:
  batch:
    job:
  #      enabled: false

  config:
    import:
      - aws-parameterstore:/config/sooum/
      - classpath:/application-core-data.yml
      - classpath:/application-cloud.yml

  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      port: ${redis.port}
      host: ${redis.host}

slack:
  webhook:
    url: ${slack.url}

# todo batch url, core url, test url로 파라미터 분리할 지 고민