spring:
  config:
    import: aws-parameterstore:/config/sooum/

  cloud:
    aws:
      credentials:
        access-key: ${accessKey}
        secret-key: ${secretKey}
      region:
        static: ap-northeast-2
      rekognition:
        credentials:
          accessKey: ${rekognition.accessKey}
          secretKey: ${rekognition.secretKey}
      s3:
        img:
          bucket: sooum-test-img
        fcm:
          bucket: sooum-test-fcm
          sdk: ${fcm.sdk}
        credentials:
          accessKey: ${s3.accessKey}
          secretKey: ${s3.secretKey}
        DEFAULT_CARD_IMG: card/default/
        USER_CARD_IMG: card/user/
        PROFILE_IMG: profile/

---

spring:
  config:
    activate:
      on-profile: prod

  cloud:
    aws:
      s3:
        img:
          bucket: sooum-img
        fcm:
          bucket: sooum-fcm
        DEFAULT_CARD_IMG: prod/card/default/
        USER_CARD_IMG: prod/card/user/
        PROFILE_IMG: prod/profile/

---

spring:
  config:
    activate:
      on-profile: test

  cloud:
    aws:
      s3:
        img:
          bucket: sooum-test-img
        fcm:
          bucket: sooum-test-fcm
        DEFAULT_CARD_IMG: card/default/
        USER_CARD_IMG: card/user/
        PROFILE_IMG: profile/