spring:
  cloud:
    aws:
      region: ap-northeast-2
      stack.auto: false
      rekognition:
        credentials:
          accessKey: ${accessKey}
          secretKey: ${secretKey}
      s3:
        img:
          bucket: sooum-img
        fcm:
          bucket: sooum-fcm
          sdk: ${FCM_SDK}
        credentials:
          accessKey: ${accessKey}
          secretKey: ${secretKey}
        DEFAULT_CARD_IMG: test/card/default/
        USER_CARD_IMG: test/card/user/
        PROFILE_IMG: test/profile/

---

spring:
  config:
    activate:
      on-profile: prod

  cloud:
    aws:
      s3:
        DEFAULT_CARD_IMG: prod/card/default/
        USER_CARD_IMG: prod/card/user/
        PROFILE_IMG: prod/profile/

---

spring:
  config:
    activate:
      on-profile: test

  cloud:
    aws:
      s3:
        DEFAULT_CARD_IMG: test/card/default/
        USER_CARD_IMG: test/card/user/
        PROFILE_IMG: test/profile/