name: 'Sooum 이슈 생성'
description: 'Sooum 이슈 템플릿'
title: '이슈 이름을 작성해주세요'
body:
  - type: input
    id: description
    attributes:
      label: '이슈 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '상세 내용(Details)'
      description: '이슈에 대해서 자세히 설명해주세요'
      value: |
        - About Details
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '체크리스트(Tasks)'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
      value: |
        - [ ] Assignees 설정
        - [ ] Label 설정
    validations:
      required: false