spring:
  config:
    import:
      - classpath:/application-core-data.yml

  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

  cloud:
    aws:
      region: ap-northeast-2
      stack.auto: false
      rekognition:
        credentials:
          accessKey: ${accessKey}
          secretKey: ${secretKey}
      s3:
        bucket: sooum-img
        credentials:
          accessKey: ${accessKey}
          secretKey: ${secretKey}

sooum:
  server:
    ip: ${IP}
    img:
      path: ${IMG_PATH}
      default-size: 50

jwt:
  key: ${JWT_KEY}
  access:
    expiration: ${ACCESS_EXP}
  refresh:
    expiration: ${REFRESH_EXP}
