spring:
  config:
    import:
      - classpath:/application-core-data.yml
      - classpath:/application-cloud.yml

  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      repositories:
        enabled: false

sooum:
  server:
    img:
      path: ${IMG_PATH}
      default-size: 50

jwt:
  key: ${JWT_KEY}
  access:
    expiration: ${ACCESS_EXP}
  refresh:
    expiration: ${REFRESH_EXP}

slack:
  webhook:
    url: ${URL}