spring:
  config:
    import:
      - classpath:/application-core-data.yml
      - classpath:/application-cloud.yml

  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      repositories:
        enabled: false

sooum:
  server:
    img:
      path: ${IMG_PATH}
      default-size: 50

jwt:
  key: ${JWT_KEY}
  access:
    expiration: ${ACCESS_EXP}
  refresh:
    expiration: ${REFRESH_EXP}

slack:
  webhook:
    url: ${URL}

exclude-auth-path-patterns:
    paths:
      - path-pattern: /docs/index.html
        method: GET
      - path-pattern: /health-check
        method: GET
      - pathPattern: /users/key
        method: GET
      - pathPattern: /users/sign-up
        method: POST
      - pathPattern: /users/login
        method: POST
      - pathPattern: /profiles/nickname/available
        method: POST
      - pathPattern: /members/suspension
        method: POST
      - pathPattern: /app/version/**
        method: GET
      - path-pattern: /settings/transfer
        method: POST
      - path-pattern: /users/token
        method: POST

exclude-ratelimiter-path-patterns:
  paths:
        - path-pattern: /notifications/unread-cnt
          method: GET
        - path-pattern: /notifications/card/unread-cnt
          method: GET
        - path-pattern: /notifications/like/unread-cnt
          method: GET
        - path-pattern: /notifications/read
          method: GET
        - path-pattern: /notifications/unread
          method: GET
        - path-pattern: /notifications/card/read
          method: GET
        - path-pattern: /notifications/card/unread
          method: GET
        - path-pattern: /notifications/like/read
          method: GET
        - path-pattern: /notifications/like/unread
          method: GET