# aws code deploy를 위해 s3로 jar파일 전송
name: SooumCI

on:
   push:
     branches:
       - production

env:
  S3_BUCKET_NAME: sooum-ci-cd
  S3_APP_SPEC_DIC_NAME: appspec
  S3_APP_SPEC_YML_NAME: appspec.yml
  S3_APP_SPEC_SCRIPT_NAME: application_start.sh
  S3_DEPLOY_FILE_NAME: deploy-sooum.zip

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew boot:external-api:build -x test

      - name: Get AWS Credential
        if: success()
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: make appspec directory
        if: success()
        run: mkdir $S3_APP_SPEC_DIC_NAME

      - name: Download S3 bucket
        if: success()
        run: |
          aws s3 sync s3://$S3_BUCKET_NAME/$S3_APP_SPEC_DIC_NAME ./$S3_APP_SPEC_DIC_NAME

      - name: Make zip file
        if: success()
        run: zip -j ./$S3_DEPLOY_FILE_NAME ./boot/external-api/build/libs/external-api-0.0.1-SNAPSHOT.jar ./$S3_APP_SPEC_DIC_NAME/$S3_APP_SPEC_YML_NAME ./$S3_APP_SPEC_DIC_NAME/$S3_APP_SPEC_SCRIPT_NAME
        shell: bash

      - name: Upload to S3
        if: success()
        run: aws s3 cp --region ap-northeast-2 ./$S3_DEPLOY_FILE_NAME s3://$S3_BUCKET_NAME/$S3_DEPLOY_FILE_NAME

      - name: Trigger CodeDeploy
        if: success()
        run: |
          aws deploy create-deployment \
          --application-name ${{secrets.AWS_CODE_DEPLOY_APPLICATION_NAME}} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{secrets.AWS_CODE_DEPLOY_DEPLOYMENT_GROUP_NAME}} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$S3_DEPLOY_FILE_NAME