# aws code deploy를 위해 s3로 jar파일 전송
name: SooumCI

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: sooum-ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew boot:external-api:build -x test

      - name: Make zip file
        run: zip -j ./sooum_deploy.zip ./boot/external-api/build/libs/external-api-0.0.1-SNAPSHOT.jar
        shell: bash

      - name: Deliver to AWS S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./sooum_deploy.zip s3://$S3_BUCKET_NAME/sooum_deploy.zip
